### ISSUE TITLE
Blocking on state changes?

### ISSUE THREAD

**Issue by dolphin278** [dolphin278/fsm#1]
There should be some option to ensure that state changes are invoked sequentially, e.g.:
1. invoke `.follow()` method once.
2. before it completes, `.follow()` once more, before first one completes
3. first method resolves, state changed
4. second method completes, state changed again.

After step 4. we can have fsm that followed denied path according to it's graph:

 A->B, A->C, no B->C, no C->B

first, invoke follow('A->B'), and before it finished, invoke follow('A->C'), so as described above, we would have following history: A->B->C or A->C->B, depending on what invocation completes first.

Looks like we need to queue state changes, or just return an error.
First approach is bad because we can consume memory by our queue, second is bad because it messes with follow semantic — valid follow invocations could return an error.

**Comment by dolphin278** [comment]
On the other side, locking mechanism may be implemented on higher application layers, that manages set of fsm and handles requests to manipulate them using appropriate technologies — like redis to store locks to be accessible from different node processes.

**Comment by sitnin** [comment]
You could handle transitions queue and just notify the sender about transition cancellation caused by invalid transition request.

**Comment by sitnin** [comment]
But wait. Why the user is working with the transitions at all? Isn't FSM should get a concrete set of ingoing and outgoing connections and react with output on changed input and give a notification about state changes to the subscriber?

**Comment by dolphin278** [comment]
Yes, but we need a place where to track ongoing transitions that should be accessible from each node process.

**Comment by dolphin278** [comment]
>  But wait. Why the user is working with the transitions at all? Isn't FSM should get a concrete set of ingoing and
>  outgoing connections and react with output on changed input and give a notification about state changes to the 
>  subscriber?

Transition starts upon request from client — whether it some application or time-driven attempt to move fsm to other state. FSM itself is passive — it don't change it state on it's own. To make them 'self-propelled' we can just add some external timer that attempts to change transition — it's surely possible, but it heavily depends on how you use fsm.

**Comment by sitnin** [comment]
Boris, FSM should be triggered with input data, it's normal case. It's shouldn't be "self-propelled". I just saying that "classic FSM" is just a bunch of inputs and outputs. Every single input change transitions the state (serially and atomically). So, it should incorporate FIFO buffer and can give a feedback on each transition results (which is a output changes). And also could notify the user through the special feedback line about invalid input data being ignored due to incompatibility with the current machine state.

It seems I think you overloaded the idea ;)

**Comment by sitnin** [comment]
Got it.
What if you just create a delegate protocol for the queue store and decouple this problem from the main library code?

**Comment by dolphin278** [comment]
Yep. It's what I am planning to do.
